apiVersion: v1
kind: Service
metadata:
  name: authorization-server
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: authorization-server
  type: LoadBalancer