apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-secret
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "0a3e6883-894e-458b-8958-e4483ecc5ff5" # ID de la Managed Identity creada
    keyvaultName: "twitter-clone-vault"
    tenantId: "8702951b-87d4-4c24-969b-4b254e6db4ce"
    objects: |
      array:
        - |
          objectName: "client-id-code-authorization"
          objectType: secret
        - |
          objectName: "client-secret-code-authorization"
          objectType: secret
        - |
          objectName: "client-id-client-credentials"
          objectType: secret
        - |
          objectName: "client-secret-client-credentials"
          objectType: secret

  secretObjects: # 👈 Esto sincroniza los valores con Kubernetes Secrets
    - secretName: authorization-secrets
      type: Opaque
      data:
        - objectName: "client-id-code-authorization"
          key: "client_id_code_authorization"
        - objectName: "client-secret-code-authorization"
          key: "client_secret_code_authorization"
        - objectName: "client-id-client-credentials"
          key: "client_id_client_credentials"
        - objectName: "client-secret-client-credentials"
          key: "client_secret_client_credentials"
