apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-secret
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<MI_CLIENT_ID>" # ID de la Managed Identity creada
    keyvaultName: "twitter-clone-vault"
    tenantId: "8702951b-87d4-4c24-969b-4b254e6db4ce"
    objects: |
      array:
        - objectName: "client_id_code_authorization"
          objectType: secret
        - objectName: "client_secret_code_authorization"
          objectType: secret
        - objectName: "client_id_client_credentials"
          objectType: secret
       -  objectName: "client_secret_client_credentials"
          objectType: secret
       -  objectName: "postgres_user"
          objectType: secret
       -  objectName: "postgres_password"
          objectType: secret
      -   objectName: "mongo_user"
          objectType: secret
      -   objectName: "mongo_password"
          objectType: secret
      -   objectName: "connection_send_notification"
          objectType: secret  
      -   objectName: "key_secret"
          objectType: secret  

  secretObjects: # 👈 Esto sincroniza los valores con Kubernetes Secrets
    - secretName: authorization-secrets
      type: Opaque
      data:
        - objectName: "client_id_code_authorization"
          key: "client_id_code_authorization"
        - objectName: "client_secret_code_authorization"
          key: "client_secret_code_authorization"
        - objectName: "client_id_client_credentials"
          key: "client_id_client_credentials"
        - objectName: "client_secret_client_credentials"
          key: "client_secret_client_credentials"
    - secretName: postgres-secrets
      type: Opaque
      data:
        - objectName: "postgres_user"
          key: "postgres_user"
        - objectName: "postgres_password"
          key: "postgres_password"
    - secretName: mongo-secrets
      type: Opaque
      data:
        - objectName: "mongo_user"
          key: "mongo_user"
        - objectName: "mongo_password"
          key: "mongo_password"
    - secretName: gateway-secrets
      type: Opaque
      data:
        - objectName: "key_secret"
          key: "key_secret"
    - secretName: service-bus-secrets
      type: Opaque
      data:
        - objectName: "connection_send_notification"
          key: "connection_send_notification"