apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-secret
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "162b2b28-cb0e-49fe-b2f0-7b01abab7778" # ID de la Managed Identity creada
    keyvaultName: "twitter-clone-vault"
    tenantId: "8702951b-87d4-4c24-969b-4b254e6db4ce"
    objects: |
      array:
        - |
          objectName: "client-id-code-authorization"
          objectType: secret
        - |
          objectName: "client-secret-code-authorization"
          objectType: secret
        - |
          objectName: "client-id-client-credentials"
          objectType: secret
        - |
          objectName: "client-secret-client-credentials"
          objectType: secret
        - |
          objectName: "postgres-user"
          objectType: secret
        - |
          objectName: "postgres-password"
          objectType: secret
        - |
          objectName: "mongo-user"
          objectType: secret
        - |
          objectName: "mongo-password"
          objectType: secret
        - |
          objectName: "connection-send-notification"
          objectType: secret  
        - |
          objectName: "key-secret"
          objectType: secret  

  secretObjects: # 👈 Esto sincroniza los valores con Kubernetes Secrets
    - secretName: authorization-secrets
      type: Opaque
      data:
        - objectName: "client-id-code-authorization"
          key: "client_id_code_authorization"

        - objectName: "client-secret-code-authorization"
          key: "client_secret_code_authorization"

        - objectName: "client-id-client-credentials"
          key: "client_id_client_credentials"

        - objectName: "client-secret-client-credentials"
          key: "client_secret_client_credentials"
    - secretName: postgres-secrets
      type: Opaque
      data:
        - objectName: "postgres-user"
          key: "postgres_user"
        - objectName: "postgres-password"
          key: "postgres_password"
    - secretName: mongo-secrets
      type: Opaque
      data:
        - objectName: "mongo-user"
          key: "mongo_user"
        - objectName: "mongo-password"
          key: "mongo_password"
    - secretName: gateway-secrets
      type: Opaque
      data:
        - objectName: "key-secret"
          key: "key_secret"
    - secretName: service-bus-secrets
      type: Opaque
      data:
        - objectName: "connection-send-notification"
          key: "connection_send_notification"