apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comments-service
  template:
    metadata:
      labels:
        app: comments-service
    spec:
      containers:
        - image: feralexis007/twitter-clone-comments-service:dev-65d45f2
          name: comments-service
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: comments-service
                  key: db_host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_password
            - name: USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: comments-service
                  key: users_url
            - name: POSTS_URL
              valueFrom:
                configMapKeyRef:
                  name: comments-service
                  key: posts_url
          volumeMounts:
            - name: azure-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: azure-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-key-vault-secret"