apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-server
data:
  client_url: http://gateway-server:8090
  auth_server: http://authorization-server:9000
  users_url: http://users-service:8080/v1/users

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-server
data:
  auth_server: http://authorization-server:9000
  redirect_url: http://gateway-server:8090/authorized
  users_url: http://users-service:8080/v1/users
  posts_url: http://posts-service:8081/v1/posts
  comments_url: http://comments-service:8082/v1/comments
  likes_url: http://likes-service:8083/v1/likes
  followers_url: http://followers-service:8084/v1/followers
  notifications_url: http://notifications-service:8085/v1/notifications

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service
data:
  db_name: users_db
  db_host: r2dbc:postgresql://postgres16:5432/users_db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-service
data:
  db_name: posts_db
  db_host: mongodb://mongo6-posts:27017/posts_db
  users_url: http://users-service:8080/v1/users
  followers_url: http://followers-service:8084/v1/followers

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: comments-service
data:
  db_name: comments_db
  db_host: mongodb://mongo6-comments:27017/comments_db
  users_url: http://users-service:8080/v1/users
  posts_url: http://posts-service:8081/v1/posts

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: likes-service
data:
  db_name: likes_db
  db_host: mongodb://mongo6-likes:27017/likes_db
  users_url: http://users-service:8080/v1/users
  posts_url: http://posts-service:8081/v1/posts
  comments_url: http://comments-service:8082/v1/comments

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: followers-service
data:
  db_name: followers_db
  db_host: mongodb://mongo6-followers:27017/followers_db
  users_url: http://users-service:8080/v1/users

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-service
data:
  db_name: notifications_db
  db_host: mongodb://mongo6-notifications:27017/notifications_db
  users_url: http://users-service:8080/v1/users
  posts_url: http://posts-service:8081/v1/posts
  comments_url: http://comments-service:8082/v1/comments