apiVersion: apps/v1
kind: Deployment
metadata:
  name: followers-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: followers-service
  template:
    metadata:
      labels:
        app: followers-service
    spec:
      containers:
        - image: feralexis007/twitter-clone-followers-service:dev-f7b9dc3
          name: followers-service
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: followers-service
                  key: db_host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_password
            - name: USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: followers-service
                  key: users_url
          volumeMounts:
            - name: azure-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: azure-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-key-vault-secret"