apiVersion: apps/v1
kind: Deployment
metadata:
  name: likes-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: likes-service
  template:
    metadata:
      labels:
        app: likes-service
    spec:
      containers:
        - image: feralexis007/twitter-clone-likes-service:dev-b585dc2
          name: likes-service
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: likes-service
                  key: db_host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_password
            - name: USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: likes-service
                  key: users_url
            - name: POSTS_URL
              valueFrom:
                configMapKeyRef:
                  name: likes-service
                  key: posts_url
            - name: COMMENTS_URL
              valueFrom:
                configMapKeyRef:
                  name: likes-service
                  key: comments_url
          volumeMounts:
            - name: azure-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: azure-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-key-vault-secret"