apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo6
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo6
  template:
    metadata:
      labels:
        app: mongo6
    spec:
      containers:
        - image: mongo:6.0
          name: mongo6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_password
          volumeMounts:
            - name: mongo
              mountPath: /data/db
            - name: azure-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: azure-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-key-vault-secret"