apiVersion: v1
kind: Secret
metadata:
  name: authorization-secrets
  namespace: dev
type: Opaque
data:
  client_id_code_authorization: Y2xpZW50ZV9hdXRob3JpemF0aW9u
  client_secret_code_authorization: MTIzNDU2
  client_id_client_credentials: Y2xpZW50ZV9jcmVkZW50aWFscw==
  client_secret_client_credentials: MTIzNDU2Nw==
---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dev
type: Opaque
data:
  postgres_user: cG9zdGdyZXM=
  postgres_password: cG9zdGdyZXM=

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: dev
type: Opaque
data:
  mongo_user: YWRtaW4=
  mongo_password: YWRtaW4=

---
apiVersion: v1
kind: Secret
metadata:
  name: service-bus-secrets
  namespace: dev
type: Opaque
data:
  connection_send_notification: RW5kcG9pbnQ9c2I6Ly90d2l0dGVyLWNsb25lLWJ1cy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PTlEODZZL0xCSHdrN21DV1dRMW9zV044ZGlSb2J5TGNKNStBU2JLam5xQnc9

---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: dev
type: Opaque
data:
  key_secret: RW5kcG9pbnQ9c2I6Ly90d2l0dGVyLWNsb25lLWJ1cy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PTlEODZZL0xCSHdrN21DV1dRMW9zV044ZGlSb2J5TGNKNStBU2JLam5xQnc9
