apiVersion: v1
kind: Service
metadata:
  name: authorization-server-dev
  namespace: development
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: authorization-server-dev
  type: ClusterIP