apiVersion: v1
kind: Service
metadata:
  name: mongo6_followers-dev
  namespace: development
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo6_followers-dev
  type: ClusterIP