apiVersion: v1
kind: Service
metadata:
  name: postgres16-dev
  namespace: development
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres16-dev
  type: ClusterIP