apiVersion: v1
kind: Service
metadata:
  name: authorization-server-prod
  namespace: production
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: authorization-server-prod
  type: ClusterIP