apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-likes-pv-prod
  namespace: development
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
    type: DirectoryOrCreate