apiVersion: v1
kind: Service
metadata:
  name: mongo6_notifications-prod
  namespace: production
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo6_notifications-prod
  type: ClusterIP