apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres16-prod
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres16-prod
  template:
    metadata:
      labels:
        app: postgres16-prod
    spec:
      containers:
        - image: postgres:16-alpine
          name: postgres16-prod
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              #value: root => esto se soloca cuando quieres poner los datso en duro
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              #value: root => esto se soloca cuando quieres poner los datso en duro
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: users-service-prod
                  key: db_name
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc-prod


