apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-prod
  namespace: production
spec:
  volumeName: postgres-pv-prod
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi