apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-prod
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service-prod
  template:
    metadata:
      labels:
        app: users-service-prod
    spec:
      containers:
        - image: feralexis007/twitter-clone-users-service:prod-0d68b9d
          name: users-service-prod
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: students-service
                  key: db_host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD